server:
  port: 8083                       # третий сервис на 8083

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        "[spring.json.value.default.type]": com.ecommerce.notificationservice.event.OrderCreatedEvent
        "[spring.json.use.type.headers]": false

centrifugo:
  api-url: http://localhost:8000        # без /api — см. комментарий в клиенте
  api-key: 4e27bc9a63c75227c490cf94c656ed87
  token-secret: pQLEUu1GgqnY0Z5fHl29OVpBd364r4zE7wqnFUmFGlE=
  token-ttl-ms: 3600000