
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/orders/**
            - id: notifications-service
              uri: ${NOTIFICATIONS_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/notifications/**
            - id: stock-service
              uri: ${STOCK_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/api/stock/**
            - id: payment-service
              uri: ${PAYMENT_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/api/payment/**
            - id: frontend-service
              uri: ${FRONTEND_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/**
jwt:
  secret: ${JWT_SECRET:c2VjcmV0LWtleS1mb3ItZWNvbW1lcmNlLWF1dGgtc2VydmljZS1kZXY=}
server:
  port: 8080

