server:
  port: 8084

spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: ecom
    password: ecom_pass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.type.mapping: stockReserved:com.ecommerce.stockservice.event.StockReserved, stockReservationFailed:com.ecommerce.stockservice.event.StockReservationFailed
        spring.json.trusted.packages: com.ecommerce.stockservice.event
    consumer:
      group-id: stock-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.type.mapping: orderCreated:com.ecommerce.stockservice.event.OrderCreatedEvent,paymentFailed:com.ecommerce.stockservice.event.PaymentFailedEvent
        spring.json.trusted.packages: com.ecommerce.stockservice.event