server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_db
    username: ecom
    password: ecom_pass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.type.mapping: paymentCompleted:com.ecommerce.paymentservice.event.PaymentCompleted,paymentFailed:com.ecommerce.paymentservice.event.PaymentFailed
        spring.json.trusted.packages: com.ecommerce.paymentservice.event
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.type.mapping: stockReserved:com.ecommerce.paymentservice.event.StockReserved
        spring.json.trusted.packages: com.ecommerce.paymentservice.event
payment.decline-threshold: 1000