server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders_db}
    username: ${SPRING_DATASOURCE_USERNAME:ecom}
    password: ${SPRING_DATASOURCE_PASSWORD:ecom_pass}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.type.mapping: orderCreated:com.ecommerce.core.event.OrderCreatedEvent
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.type.mapping: paymentCompleted:com.ecommerce.core.event.PaymentCompleted,stockReservationFailed:com.ecommerce.core.event.StockReservationFailedEvent,paymentFailed:com.ecommerce.core.event.PaymentFailed
        spring.json.trusted.packages: com.ecommerce.core.event

orders.events.topic.name: orders-events
stock.commands.topic.name: stock-commands